### ISSUE TITLE
Example fails successfully

### ISSUE THREAD

**Issue by paleite** [felixmosh/turborepo-gh-artifacts-example#1]
I forked the example and ran the job, and CI says it passes, but when I look in the post-action, it says server-token wasn't set. I also see in `lint` and `build` that the token is empty.

Passing in CI:
![image](https://user-images.githubusercontent.com/4430528/217508546-2eb0ae60-4e74-4a45-ad27-8d64e66c0e9b.png)

But there were errors:
![image](https://user-images.githubusercontent.com/4430528/217508336-dde4e31d-19d4-4790-a40c-e9294134ac6b.png)

Empty token:
![image](https://user-images.githubusercontent.com/4430528/217508769-75285be5-7c85-4266-b4d1-164a342fad64.png)

Post Turborepo local server not instantiated:
![image](https://user-images.githubusercontent.com/4430528/217508876-7ef3b21c-4458-42ea-b697-c1cd2785378e.png)

And the permissions look like follows. In an attempt to debug I changed the permissions to allow write.
![image](https://user-images.githubusercontent.com/4430528/217509246-9f5910e6-5bdb-46d5-ad27-fa30d6247e96.png)

**Comment by felixmosh** [comment]
Hi @paleite thank you for reporting it.

Since the error is on the "local" server your workflow won't fail.

You need to provide a **secret** with the name `TURBO_SERVER_TOKEN` in your forked repo, otherwise, the local server will ignore turbo repo requests. (and still not fail, just the cache won't be save).

The Idea with this token is to make sure that the only one that communicates with the local server, is your defined task.

**Comment by paleite** [comment]
Thanks, I added a token, but it used special characters that weren't escaped, which broke the action. I'll report it in the action's repo instead.

**Comment by felixmosh** [comment]
This token is an env variable, and it can be anything specific for the workflow... meaning, it's value is not so important, I've explained above the propose of it....

**Comment by paleite** [comment]
Now it works! Thanks a lot 😃

I assumed it was optional, because the docs didn't mention anything about creating a repo secret and because the docs said the action only required 1 input (`GITHUB_TOKEN`): https://github.com/felixmosh/turborepo-gh-artifacts#action-inputs

**Comment by felixmosh** [comment]
It was required, probably the move to use `TURBO_TOKEN` env var it omitted, not sure why, I'll check :]

**Comment by paleite** [comment]
Awesome! Appreciate you being so responsive 👍
